"""Generate reference docs from the code (ADR-0011).

Writes, under ``docs/reference/``:

- ``openapi.json``: the API contract; the TypeScript client is generated from it
- ``permissions.md``: permissions per role, and the access rule of every route
- ``configuration.md``: every ``FH_*`` environment variable
- ``database.md``: an ER diagram of every table

Usage (from ``apps/api``)::

    uv run python -m family_hub.tools.generate          # write files
    uv run python -m family_hub.tools.generate --check  # fail if any file is stale
"""

import argparse
import json
import sys
from collections.abc import Callable
from datetime import timedelta
from pathlib import Path
from typing import Any

from pydantic import SecretStr
from sqlalchemy import Table

import family_hub.models  # noqa: F401  (registers all models)
from family_hub.config import Settings
from family_hub.db import Base
from family_hub.main import API_PREFIX, create_app
from family_hub.modules import MODULES
from family_hub.platform.authz.access import module_routes, route_access
from family_hub.platform.authz.registry import Authorizer
from family_hub.platform.households.models import Role
from family_hub.platform.module import PLATFORM

REPO = Path(__file__).resolve().parents[5]
REFERENCE = REPO / "docs" / "reference"
HEADER = (
    "<!-- Generated by apps/api/src/family_hub/tools/generate.py. Do not edit; "
    "run `make generate`. -->\n\n"
)


def openapi() -> str:
    # Development settings so the spec is served; it is identical in every environment.
    app = create_app(Settings(environment="development"))
    return json.dumps(app.openapi(), indent=2, ensure_ascii=False, sort_keys=True) + "\n"


def permissions() -> str:
    modules = [PLATFORM, *MODULES]
    authorizer = Authorizer(modules)
    roles = list(Role)
    lines = [
        HEADER + "# Permissions\n",
        "Roles inherit: `owner` ⊇ `adult` ⊇ `child` (AUTHZ-3). "
        "See [authorization.md](../platform/authorization.md).\n",
        "## Permissions by role\n",
        "| Permission | Description | " + " | ".join(r.value for r in roles) + " |",
        "|---|---|" + "|".join(":-:" for _ in roles) + "|",
    ]
    for name, permission in sorted(authorizer.permissions.items()):
        marks = " | ".join("✓" if authorizer.allows(r, name) else "—" for r in roles)
        lines.append(f"| `{name}` | {permission.description} | {marks} |")
    lines += ["", "## Access rule per route\n", "| Method | Path | Access |", "|---|---|---|"]
    rows = []
    for path, route in module_routes(modules, API_PREFIX):
        access = route_access(route)[0]
        rule = f"`{access.permission}`" if access.permission else access.kind
        rows += [(path, method, rule) for method in sorted(route.methods or ())]
    lines += [f"| {method} | `{path}` | {rule} |" for path, method, rule in sorted(rows)]
    return "\n".join(lines) + "\n"


def _default(value: Any) -> str:
    """Render a default as it would be written in an environment variable."""
    if isinstance(value, SecretStr):
        return "*(insecure dev value; required in production)*"
    if isinstance(value, bool):
        return f"`{str(value).lower()}`"
    if isinstance(value, timedelta):
        seconds = int(value.total_seconds())
        iso = f"P{value.days}D" if seconds % 86400 == 0 else f"PT{seconds}S"
        return f"`{iso}`"
    return f"`{value}`"


def configuration() -> str:
    prefix = Settings.model_config.get("env_prefix", "")
    lines = [
        HEADER + "# Configuration\n",
        "Environment variables read by the API, or `apps/api/.env`. "
        "Durations use ISO 8601, e.g. `P14D`.\n",
        "| Variable | Default | Description |",
        "|---|---|---|",
    ]
    for name, field in Settings.model_fields.items():
        description = " ".join((field.description or "").split()).replace("``", "`")
        lines.append(f"| `{prefix}{name.upper()}` | {_default(field.default)} | {description} |")
    return "\n".join(lines) + "\n"


def _entity(table: Table) -> str:
    return f"{table.schema}_{table.name}" if table.schema else table.name


def database() -> str:
    tables = sorted(Base.metadata.tables.values(), key=_entity)
    lines = [
        HEADER + "# Database\n",
        "Tables and foreign keys, from the SQLAlchemy models. Entity names are "
        "`<schema>_<table>`. Audit events reference IDs without foreign keys (AUDIT-4).\n",
        "```mermaid",
        "erDiagram",
    ]
    for table in tables:
        lines.append(f"  {_entity(table)} {{")
        for column in table.columns:
            keys = ",".join(
                k for k, on in (("PK", column.primary_key), ("FK", bool(column.foreign_keys))) if on
            )
            kind = type(column.type).__name__
            lines.append(f"    {kind} {column.name}{' ' + keys if keys else ''}")
        lines.append("  }")
    for table in tables:
        for fk in sorted(table.foreign_keys, key=lambda f: f.parent.name):
            target = _entity(fk.column.table)
            lines.append(f'  {target} ||--o{{ {_entity(table)} : "{fk.parent.name}"')
    lines.append("```")
    return "\n".join(lines) + "\n"


GENERATORS: dict[str, Callable[[], str]] = {
    "openapi.json": openapi,
    "permissions.md": permissions,
    "configuration.md": configuration,
    "database.md": database,
}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if any file is stale")
    args = parser.parse_args()

    stale = []
    REFERENCE.mkdir(parents=True, exist_ok=True)
    for name, generate in GENERATORS.items():
        path = REFERENCE / name
        content = generate()
        current = path.read_text(encoding="utf-8") if path.exists() else None
        if content == current:
            continue
        if args.check:
            stale.append(name)
        else:
            path.write_text(content, encoding="utf-8")
            print(f"wrote docs/reference/{name}")
    if stale:
        print("stale (run `make generate`): " + ", ".join(f"docs/reference/{n}" for n in stale))
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
