// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { AuthCurrentSessionData, AuthCurrentSessionResponses, AuthLoginData, AuthLoginErrors, AuthLoginResponses, AuthLogoutData, AuthLogoutResponses, HealthLivenessData, HealthLivenessResponses, HealthReadinessData, HealthReadinessErrors, HealthReadinessResponses, HouseholdsGetHouseholdData, HouseholdsGetHouseholdErrors, HouseholdsGetHouseholdResponses, HouseholdsListAuditEventsData, HouseholdsListAuditEventsErrors, HouseholdsListAuditEventsResponses, HouseholdsUpdateHouseholdData, HouseholdsUpdateHouseholdErrors, HouseholdsUpdateHouseholdResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Log in
 */
export const authLogin = <ThrowOnError extends boolean = false>(options: Options<AuthLoginData, ThrowOnError>): RequestResult<AuthLoginResponses, AuthLoginErrors, ThrowOnError> => (options.client ?? client).post<AuthLoginResponses, AuthLoginErrors, ThrowOnError>({
    url: '/api/v1/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Log out
 *
 * Revoke the current session, if any, and clear the cookie. Always succeeds.
 */
export const authLogout = <ThrowOnError extends boolean = false>(options?: Options<AuthLogoutData, ThrowOnError>): RequestResult<AuthLogoutResponses, unknown, ThrowOnError> => (options?.client ?? client).post<AuthLogoutResponses, unknown, ThrowOnError>({ url: '/api/v1/auth/logout', ...options });

/**
 * Current session
 */
export const authCurrentSession = <ThrowOnError extends boolean = false>(options?: Options<AuthCurrentSessionData, ThrowOnError>): RequestResult<AuthCurrentSessionResponses, unknown, ThrowOnError> => (options?.client ?? client).get<AuthCurrentSessionResponses, unknown, ThrowOnError>({ url: '/api/v1/auth/session', ...options });

/**
 * Liveness
 *
 * The process is up. Does not touch dependencies.
 */
export const healthLiveness = <ThrowOnError extends boolean = false>(options?: Options<HealthLivenessData, ThrowOnError>): RequestResult<HealthLivenessResponses, unknown, ThrowOnError> => (options?.client ?? client).get<HealthLivenessResponses, unknown, ThrowOnError>({ url: '/api/v1/health', ...options });

/**
 * Readiness
 *
 * PostgreSQL and Redis are reachable.
 */
export const healthReadiness = <ThrowOnError extends boolean = false>(options?: Options<HealthReadinessData, ThrowOnError>): RequestResult<HealthReadinessResponses, HealthReadinessErrors, ThrowOnError> => (options?.client ?? client).get<HealthReadinessResponses, HealthReadinessErrors, ThrowOnError>({ url: '/api/v1/health/ready', ...options });

/**
 * Household and its members
 */
export const householdsGetHousehold = <ThrowOnError extends boolean = false>(options: Options<HouseholdsGetHouseholdData, ThrowOnError>): RequestResult<HouseholdsGetHouseholdResponses, HouseholdsGetHouseholdErrors, ThrowOnError> => (options.client ?? client).get<HouseholdsGetHouseholdResponses, HouseholdsGetHouseholdErrors, ThrowOnError>({ url: '/api/v1/households/{household_id}', ...options });

/**
 * Rename or change time zone
 */
export const householdsUpdateHousehold = <ThrowOnError extends boolean = false>(options: Options<HouseholdsUpdateHouseholdData, ThrowOnError>): RequestResult<HouseholdsUpdateHouseholdResponses, HouseholdsUpdateHouseholdErrors, ThrowOnError> => (options.client ?? client).patch<HouseholdsUpdateHouseholdResponses, HouseholdsUpdateHouseholdErrors, ThrowOnError>({
    url: '/api/v1/households/{household_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Recent audit events, newest first
 */
export const householdsListAuditEvents = <ThrowOnError extends boolean = false>(options: Options<HouseholdsListAuditEventsData, ThrowOnError>): RequestResult<HouseholdsListAuditEventsResponses, HouseholdsListAuditEventsErrors, ThrowOnError> => (options.client ?? client).get<HouseholdsListAuditEventsResponses, HouseholdsListAuditEventsErrors, ThrowOnError>({ url: '/api/v1/households/{household_id}/audit-events', ...options });
