// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AuditEventOut
 */
export type AuditEventOut = {
    /**
     * Action
     */
    action: string;
    /**
     * Actor User Id
     */
    actor_user_id: string | null;
    /**
     * After
     */
    after: {
        [key: string]: unknown;
    } | null;
    /**
     * Before
     */
    before: {
        [key: string]: unknown;
    } | null;
    /**
     * Entity Id
     */
    entity_id: string | null;
    /**
     * Entity Type
     */
    entity_type: string;
    /**
     * Id
     */
    id: string;
    /**
     * Occurred At
     */
    occurred_at: string;
    /**
     * Source
     */
    source: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * HouseholdOut
 */
export type HouseholdOut = {
    /**
     * Id
     */
    id: string;
    /**
     * Members
     */
    members: Array<MemberOut>;
    /**
     * Name
     */
    name: string;
    /**
     * Timezone
     */
    timezone: string;
};

/**
 * HouseholdUpdate
 *
 * Only the fields that are sent are changed.
 */
export type HouseholdUpdate = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Timezone
     *
     * IANA name, e.g. Asia/Taipei
     */
    timezone?: string | null;
};

/**
 * Liveness
 */
export type Liveness = {
    /**
     * Status
     */
    status: 'ok';
};

/**
 * LoginRequest
 */
export type LoginRequest = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
};

/**
 * MemberOut
 */
export type MemberOut = {
    /**
     * Display Name
     */
    display_name: string;
    role: Role;
    /**
     * User Id
     */
    user_id: string;
};

/**
 * MembershipOut
 */
export type MembershipOut = {
    /**
     * Household Id
     */
    household_id: string;
    /**
     * Household Name
     */
    household_name: string;
    role: Role;
};

/**
 * Readiness
 */
export type Readiness = {
    /**
     * Database
     */
    database: 'ok' | 'error';
    /**
     * Redis
     */
    redis: 'ok' | 'error';
    /**
     * Status
     */
    status: 'ok' | 'error';
};

/**
 * Role
 *
 * Built-in household roles (see docs/architecture.md).
 */
export type Role = 'owner' | 'adult' | 'child';

/**
 * SessionOut
 */
export type SessionOut = {
    /**
     * Csrf Token
     */
    csrf_token: string;
    /**
     * Memberships
     */
    memberships: Array<MembershipOut>;
    user: UserOut;
};

/**
 * UserOut
 */
export type UserOut = {
    /**
     * Display Name
     */
    display_name: string;
    /**
     * Email
     */
    email: string;
    /**
     * Id
     */
    id: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
    /**
     * Input
     */
    input?: unknown;
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type AuthLoginData = {
    body: LoginRequest;
    path?: never;
    query?: never;
    url: '/api/v1/auth/login';
};

export type AuthLoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthLoginError = AuthLoginErrors[keyof AuthLoginErrors];

export type AuthLoginResponses = {
    /**
     * Successful Response
     */
    200: SessionOut;
};

export type AuthLoginResponse = AuthLoginResponses[keyof AuthLoginResponses];

export type AuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/logout';
};

export type AuthLogoutResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type AuthLogoutResponse = AuthLogoutResponses[keyof AuthLogoutResponses];

export type AuthCurrentSessionData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/auth/session';
};

export type AuthCurrentSessionResponses = {
    /**
     * Successful Response
     */
    200: SessionOut;
};

export type AuthCurrentSessionResponse = AuthCurrentSessionResponses[keyof AuthCurrentSessionResponses];

export type HealthLivenessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type HealthLivenessResponses = {
    /**
     * Successful Response
     */
    200: Liveness;
};

export type HealthLivenessResponse = HealthLivenessResponses[keyof HealthLivenessResponses];

export type HealthReadinessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health/ready';
};

export type HealthReadinessErrors = {
    /**
     * Service Unavailable
     */
    503: Readiness;
};

export type HealthReadinessError = HealthReadinessErrors[keyof HealthReadinessErrors];

export type HealthReadinessResponses = {
    /**
     * Successful Response
     */
    200: Readiness;
};

export type HealthReadinessResponse = HealthReadinessResponses[keyof HealthReadinessResponses];

export type HouseholdsGetHouseholdData = {
    body?: never;
    path: {
        /**
         * Household Id
         */
        household_id: string;
    };
    query?: never;
    url: '/api/v1/households/{household_id}';
};

export type HouseholdsGetHouseholdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HouseholdsGetHouseholdError = HouseholdsGetHouseholdErrors[keyof HouseholdsGetHouseholdErrors];

export type HouseholdsGetHouseholdResponses = {
    /**
     * Successful Response
     */
    200: HouseholdOut;
};

export type HouseholdsGetHouseholdResponse = HouseholdsGetHouseholdResponses[keyof HouseholdsGetHouseholdResponses];

export type HouseholdsUpdateHouseholdData = {
    body: HouseholdUpdate;
    path: {
        /**
         * Household Id
         */
        household_id: string;
    };
    query?: never;
    url: '/api/v1/households/{household_id}';
};

export type HouseholdsUpdateHouseholdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HouseholdsUpdateHouseholdError = HouseholdsUpdateHouseholdErrors[keyof HouseholdsUpdateHouseholdErrors];

export type HouseholdsUpdateHouseholdResponses = {
    /**
     * Successful Response
     */
    200: HouseholdOut;
};

export type HouseholdsUpdateHouseholdResponse = HouseholdsUpdateHouseholdResponses[keyof HouseholdsUpdateHouseholdResponses];

export type HouseholdsListAuditEventsData = {
    body?: never;
    path: {
        /**
         * Household Id
         */
        household_id: string;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/households/{household_id}/audit-events';
};

export type HouseholdsListAuditEventsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type HouseholdsListAuditEventsError = HouseholdsListAuditEventsErrors[keyof HouseholdsListAuditEventsErrors];

export type HouseholdsListAuditEventsResponses = {
    /**
     * Response Households List Audit Events
     *
     * Successful Response
     */
    200: Array<AuditEventOut>;
};

export type HouseholdsListAuditEventsResponse = HouseholdsListAuditEventsResponses[keyof HouseholdsListAuditEventsResponses];
